## -*- encoding: utf-8 -*-
## This file (directComparison.sagetex.sage) was *autogenerated* from directComparison.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('directComparison', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
