## -*- encoding: utf-8 -*-
## This file (chapter2Review161.sagetex.sage) was *autogenerated* from chapter2Review161.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('chapter2Review161', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
