## -*- encoding: utf-8 -*-
## This file (test3Review.sagetex.sage) was *autogenerated* from test3Review.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('test3Review', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
