## -*- encoding: utf-8 -*-
## This file (intervalConvergence.sagetex.sage) was *autogenerated* from intervalConvergence.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('intervalConvergence', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
