## -*- encoding: utf-8 -*-
## This file (integralTest.sagetex.sage) was *autogenerated* from integralTest.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('integralTest', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
