## -*- encoding: utf-8 -*-
## This file (uSub2.sagetex.sage) was *autogenerated* from uSub2.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('uSub2', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
