## -*- encoding: utf-8 -*-
## This file (calc2Book.sagetex.sage) was *autogenerated* from calc2Book.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('calc2Book', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
