## -*- encoding: utf-8 -*-
## This file (area.sagetex.sage) was *autogenerated* from area.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('area', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
